import type { Labs } from '.';

export const LabData: Labs[] = [
  {
    id: 'b5f3a7c4-1c56-4f9e-a926-5c9f6d837c89',
    name: 'Thiết kế vi mạch và hệ thống nhúng',
    description:
      "Thiết kế vi mạch (VLSI - Very Large Scale Integration) là một lĩnh vực kỹ thuật đặc thù trong ngành điện tử, chuyên về thiết kế và phát triển các mạch tích hợp có mật độ linh kiện rất cao. Vi mạch là nền tảng của hầu hết các thiết bị điện tử ngày nay, từ điện thoại thông minh, máy tính cá nhân đến các hệ thống ô tô và các thiết bị IoT (Internet of Things). Thiết kế vi mạch đòi hỏi sự hiểu biết sâu rộng về cả phần cứng và phần mềm, cũng như các công cụ CAD (Computer-Aided Design) phức tạp để tạo ra các chip có thể thực hiện hàng triệu hoặc thậm chí hàng tỷ hoạt động mỗi giây.\n\nQuy trình thiết kế vi mạch bắt đầu từ việc xác định các yêu cầu hệ thống và lên kế hoạch cho cấu trúc chip. Tiếp theo, các kỹ sư tiến hành thiết kế các thành phần chức năng của vi mạch, bao gồm các mạch số và tương tự. Sau khi thiết kế xong, vi mạch được mô phỏng và kiểm tra để đảm bảo rằng nó hoạt động đúng như mong muốn. Nếu mọi thứ đều ổn, vi mạch sẽ được gửi đi để chế tạo trong các nhà máy sản xuất chip. Quy trình này có thể kéo dài hàng tháng hoặc thậm chí hàng năm, phụ thuộc vào mức độ phức tạp của chip.\n\nHệ thống nhúng (Embedded Systems) là các hệ thống điện tử được thiết kế để thực hiện các chức năng cụ thể trong một thiết bị lớn hơn. Chúng được 'nhúng' vào trong thiết bị và có thể bao gồm cả phần cứng lẫn phần mềm. Hệ thống nhúng có mặt trong hầu hết các thiết bị công nghệ hiện đại như điện thoại di động, máy ảnh kỹ thuật số, thiết bị gia dụng thông minh, và xe hơi tự hành.\n\nViệc kết hợp giữa thiết kế vi mạch và hệ thống nhúng tạo ra các sản phẩm có khả năng tối ưu hóa hiệu năng và tiêu thụ năng lượng thấp. Các vi mạch được thiết kế để đáp ứng yêu cầu cụ thể của hệ thống nhúng, từ việc xử lý tín hiệu, quản lý dữ liệu đến thực hiện các thuật toán phức tạp. Sự tích hợp này cho phép các thiết bị nhúng hoạt động nhanh hơn, hiệu quả hơn và tiết kiệm năng lượng hơn.\n\nỨng dụng của vi mạch và hệ thống nhúng rất rộng lớn. Trong công nghiệp ô tô, các hệ thống nhúng được sử dụng để kiểm soát động cơ, hệ thống phanh và hệ thống giải trí. Trong y tế, vi mạch và hệ thống nhúng giúp theo dõi tình trạng sức khỏe và hỗ trợ các thiết bị cấy ghép. Tuy nhiên, việc phát triển các vi mạch và hệ thống nhúng cũng đối mặt với nhiều thách thức như yêu cầu về hiệu suất cao, kích thước nhỏ gọn và tiêu thụ năng lượng thấp.\n\nTrong tương lai, thiết kế vi mạch và hệ thống nhúng sẽ tiếp tục phát triển mạnh mẽ cùng với sự tiến bộ của công nghệ. Với sự gia tăng về nhu cầu của các thiết bị thông minh và kết nối, các kỹ sư sẽ tiếp tục đẩy mạnh việc tích hợp vi mạch và hệ thống nhúng để tạo ra các sản phẩm tiên tiến hơn. Công nghệ như trí tuệ nhân tạo (AI) và học máy (ML) sẽ ngày càng được tích hợp vào các hệ thống nhúng, mở ra các khả năng mới cho các thiết bị thông minh.\n\nThiết kế vi mạch và hệ thống nhúng không chỉ là những lĩnh vực kỹ thuật phức tạp mà còn là những yếu tố cốt lõi thúc đẩy sự phát triển của công nghệ hiện đại. Sự kết hợp giữa vi mạch và hệ thống nhúng đang tạo ra những thay đổi lớn trong cách chúng ta sống và làm việc, từ việc cải thiện hiệu suất của các thiết bị điện tử đến việc tạo ra các giải pháp thông minh cho các thách thức toàn cầu. Sự phát triển trong các lĩnh vực này hứa hẹn mang lại nhiều tiến bộ đột phá trong tương lai, góp phần xây dựng một thế giới kết nối và thông minh hơn.",
    image_urls: [
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEje0t9MqvOy7ydtuiyFNrJjG6R52EwYP1FmY4Qr7zzTIcOL7OsLsp_2QVu8k4_L9YCNajRppCinGOIRfwlDkAmwX-jtZQg5zgTQ7IkMdCIJdO0_iw6J1immMIGofnio9CA9rRNF-wRK8qPzHqKoYBQQliWhofsUsN8yrDdg4fmwz9o48yCWGZnQ4bLUqY8/w0/lo-trinh-hoc-thiet-ke-vi-mach-dien-tu-cho-nguoi-moi-bat-dau.jpg',
    ],
    teacher_ids: ['wzoCkgV', 'eDgUzvz'],
    created_at: new Date(new Date().setDate(new Date().getDate() - 1)),
    updated_at: new Date(),
    is_open: true,
    number_of_students: 12,
    salary: 20,
    specialized: 'Điện tử - Viễn thông - ĐH Leibniz Hannover',
    topic_ids: ['1'],
    working_time: 'parttime',
  },
  {
    id: 'd5a26b99-0cff-410a-bcde-da6f49f30209',
    name: 'Kỹ thuật y sinh',
    description:
      'Kỹ thuật y sinh, đôi khi còn được gọi là kỹ thuật y học, là một lĩnh vực nghiên cứu và ứng dụng công nghệ trong y học để giải quyết các vấn đề sức khỏe của con người. Tại giao điểm giữa ngành kỹ thuật và y học, kỹ thuật y sinh sử dụng các nguyên lý kỹ thuật, điện tử, máy tính, và khoa học vật lý để phát triển các giải pháp y tế tiên tiến. Sứ mệnh của kỹ thuật y sinh là cải thiện chất lượng cuộc sống và nâng cao hiệu suất trong chẩn đoán, điều trị và chăm sóc sức khỏe.\n\nTrong thế kỷ 21, kỹ thuật y sinh đã phát triển mạnh mẽ nhờ vào sự tiến bộ của công nghệ thông tin và vi mạch điện tử. Các thiết bị y tế thông minh, hệ thống theo dõi sức khỏe, và công nghệ hỗ trợ phẫu thuật đang ngày càng trở nên phổ biến và tiện ích hơn. Ví dụ, các máy đo nhịp tim thông minh có khả năng theo dõi và ghi lại dữ liệu về nhịp tim của người dùng, từ đó cung cấp thông tin quan trọng cho việc đánh giá sức khỏe tim mạch.\n\nMột lĩnh vực quan trọng của kỹ thuật y sinh là vi mạch và hệ thống nhúng. Các vi mạch điện tử được thiết kế để tích hợp trong các thiết bị y tế, từ máy đo huyết áp đến các thiết bị hỗ trợ hô hấp. Sự kết hợp giữa vi mạch và hệ thống nhúng giúp cải thiện hiệu suất và chính xác của các thiết bị y tế, đồng thời giảm thiểu kích thước và tiêu thụ năng lượng. Các hệ thống nhúng có thể được sử dụng để điều khiển các thiết bị y tế tự động, thu thập dữ liệu y tế, và gửi dữ liệu đến các hệ thống quản lý sức khỏe.\n\nNgoài ra, kỹ thuật y sinh còn liên quan đến nghiên cứu và phát triển các công nghệ mới như trí tuệ nhân tạo (AI) và học máy (ML). Các thuật toán AI và ML được áp dụng trong phân tích dữ liệu y tế để phát hiện bệnh tự động, dự đoán kết quả điều trị, và tối ưu hóa quá trình chẩn đoán và điều trị.\n\nVới sự tiến bộ của công nghệ, kỹ thuật y sinh đang mở ra những tiềm năng mới trong việc cải thiện chăm sóc sức khỏe và phát triển các giải pháp y tế tiên tiến. Sự kết hợp giữa kỹ thuật y sinh, vi mạch và hệ thống nhúng hứa hẹn mang lại những tiến bộ lớn trong việc chẩn đoán và điều trị bệnh, cũng như cải thiện chất lượng cuộc sống của con người.',
    image_urls: [
      'https://duhoctrawise.edu.vn/wp-content/uploads/2023/06/1-33.jpg',
    ],
    teacher_ids: ['5', '15'],
    created_at: new Date(new Date().setDate(new Date().getDate() - 2)),
    updated_at: new Date(),
    is_open: true,
    number_of_students: 8,
    salary: 23,
    specialized: 'Điện tử - Viễn thông - ĐH Leibniz Hannover',
    topic_ids: ['2', '3'],
    working_time: 'fulltime',
  },
  {
    id: '951fc2fb-3397-4f90-97b8-95f9f43a8c75',
    name: 'Cảm biến thông minh',
    description:
      'Cảm biến thông minh đóng vai trò quan trọng trong việc thu thập dữ liệu và giám sát môi trường xung quanh một cách hiệu quả và tự động. Sự kết hợp giữa công nghệ cảm biến và các hệ thống thông tin cho phép các thiết bị này trở nên linh hoạt và thông minh hơn, từ đó mang lại nhiều ứng dụng hữu ích trong đời sống hàng ngày.\n\nCảm biến thông minh có khả năng phát hiện và đo lường các thông số vật lý như nhiệt độ, ánh sáng, độ ẩm, độ rung, và áp suất. Thông tin thu thập được từ các cảm biến này có thể được sử dụng để giám sát môi trường sống, kiểm soát điều kiện làm việc, và tự động hoá các quy trình sản xuất.\n\nTrong ngành công nghiệp, cảm biến thông minh được sử dụng để giám sát và điều khiển các quy trình sản xuất, từ sản xuất ô tô đến chế biến thực phẩm. Cảm biến có thể được tích hợp vào các thiết bị tự động hóa để theo dõi chất lượng sản phẩm và đảm bảo an toàn trong quá trình sản xuất.\n\nNgoài ra, trong các ứng dụng thông minh nhà ở, cảm biến thông minh có thể được sử dụng để giám sát nhiệt độ và độ ẩm trong nhà, điều khiển hệ thống chiếu sáng và điều hòa không khí tự động, và bảo vệ an ninh cho ngôi nhà.\n\nỞ mức độ cá nhân, cảm biến thông minh có thể được sử dụng trong các thiết bị đeo thông minh như đồng hồ thông minh và vòng đeo sức khỏe để theo dõi hoạt động thể chất, giấc ngủ, và sức khỏe tổng thể của người dùng.\n\nVới sự phát triển của công nghệ, cảm biến thông minh sẽ tiếp tục đóng vai trò quan trọng trong việc xây dựng một môi trường sống thông minh và tiện ích hơn. Sự tích hợp của cảm biến thông minh vào các thiết bị và hệ thống sẽ mang lại nhiều lợi ích về tiện nghi, an toàn, và tiết kiệm năng lượng cho người dùng.',
    image_urls: [
      'https://cdn.tgdd.vn/hoi-dap/1322322/cam-bien-thong-minh-la-gi-co-nhung-loai-nao-ung-dung-ra-sao%20(3).jpg',
    ],
    teacher_ids: ['6', '18'],
    language: 'english',
    created_at: new Date(new Date().setDate(new Date().getDate() - 3)),
    updated_at: new Date(),
    is_open: true,
    number_of_students: 5,
    salary: 30,
    specialized: 'Kỹ thuật điều khiển & Tự động hóa',
    topic_ids: ['10', '12'],
    working_time: 'fulltime',
  },
  {
    id: 'f5e6e4b2-7d8b-4f2e-9c7b-6d0f3b1b2e2b',
    name: 'Công nghệ Blockchain',
    description:
      'Blockchain là một công nghệ lưu trữ và truyền thông tin một cách an toàn và minh bạch. Được biết đến ban đầu qua việc hỗ trợ tiền điện tử Bitcoin, blockchain ngày nay đã mở rộng ứng dụng của mình vào nhiều lĩnh vực khác nhau như tài chính, y tế, bất động sản, và quản lý chuỗi cung ứng.\n\nMột blockchain là một chuỗi các khối dữ liệu được lưu trữ trên nhiều máy tính khác nhau, mỗi khối chứa thông tin về các giao dịch hoặc sự kiện cụ thể. Khi một khối mới được tạo ra, nó sẽ được kết nối với các khối trước đó thông qua một quá trình mã hóa đặc biệt, tạo ra một chuỗi dữ liệu không thể thay đổi hoặc xóa bỏ. Điều này giúp đảm bảo tính toàn vẹn và bảo mật của dữ liệu trong blockchain.\n\nMột trong những ứng dụng phổ biến nhất của blockchain là trong lĩnh vực tài chính. Công nghệ này cho phép việc chuyển tiền và thực hiện các giao dịch một cách an toàn và minh bạch, mà không cần sự can thiệp của bên thứ ba như ngân hàng hoặc tổ chức tài chính trung gian. Blockchain cũng được sử dụng để tạo ra các hợp đồ nguồn tài chính phi tập trung (DeFi) như vay mượn, gửi tiền, và giao dịch tiền điện tử.\n\nNgoài ra, blockchain còn có ứng dụng trong lĩnh vực y tế để quản lý dữ liệu bệnh án, theo dõi nguồn gốc của các loại thuốc, và bảo vệ quyền riêng tư của bệnh nhân. Trong lĩnh vực bất động sản, blockchain có thể được sử dụng để xác minh thông tin về quyền sở hữu và lịch sử giao dịch của một tài sản.\n\nCông nghệ blockchain cũng có thể giúp cải thiện quản lý chuỗi cung ứng bằng cách theo dõi nguồn gốc của các sản phẩm, giảm thiểu rủi ro gian lận và giả mạo, và tăng cường minh bạch trong quá trình vận chuyển và lưu trữ hàng hóa.\n\nVới sự phát triển của công nghệ, blockchain hứa hẹn mang lại nhiều cơ hội mới cho các lĩnh vực khác nhau. Sự kết hợp giữa blockchain và các công nghệ khác như trí tuệ nhân tạo (AI) và học máy (ML) sẽ mở ra những tiềm năng mới trong việc tạo ra các giải pháp sáng tạo và hiệu quả cho xã hội.',
    image_urls: [
      'https://cdn.thuvienphapluat.vn/uploads/tintuc/2024/03/25/nen-tang-blockchain.jpg',
      'https://images.fpt.shop/unsafe/filters:quality(90)/fptshop.com.vn/uploads/images/tin-tuc/138522/Originals/blockchain-la-gi-01.jpg',
    ],
    teacher_ids: ['7', '19'],
    language: 'english',
    created_at: new Date(new Date().setDate(new Date().getDate() - 10)),
    updated_at: new Date(),
    is_open: true,
    number_of_students: 10,
    salary: 25,
    specialized: 'Công nghệ Thông tin Global ICT',
    topic_ids: ['4', '5'],
    working_time: 'fulltime',
  },
  {
    id: '565643a5-a4b1-454f-be45-ca09065b3cec',
    name: 'Công nghệ AI và Machine Learning',
    description:
      'Trí tuệ nhân tạo (AI) và học máy (ML) là hai lĩnh vực công nghệ đang phát triển mạnh mẽ và có ứng dụng rộng rãi trong nhiều lĩnh vực khác nhau. AI và ML giúp máy tính học hỏi và tự động hoá các tác vụ mà trước đây chỉ có con người mới có thể thực hiện được.\n\nTrí tuệ nhân tạo (AI) là lĩnh vực nghiên cứu và phát triển các hệ thống máy tính có khả năng thực hiện các tác vụ thông minh mà trước đây chỉ có con người mới có thể thực hiện được. Các ứng dụng của AI bao gồm nhận dạng giọng nói, nhận dạng hình ảnh, xử lý ngôn ngữ tự nhiên, và học máy.\n\nHọc máy (ML) là một phần của trí tuệ nhân tạo, tập trung vào việc phát triển các thuật toán và mô hình máy học có khả năng học hỏi từ dữ liệu và cải thiện hiệu suất theo thời gian. Các ứng dụng của học máy bao gồm dự đoán, phân loại, phân cụm, và học tăng cường.\n\nAI và ML có nhiều ứng dụng trong thế giới thực, từ công nghệ thông tin đến y tế, tài chính, và sản xuất. Trong công nghệ thông tin, AI và ML được sử dụng để cải thiện trải nghiệm người dùng, tối ưu hóa quy trình làm việc, và bảo vệ an ninh thông tin. Trong y tế, AI và ML giúp phân tích dữ liệu y tế, dự đoán bệnh tật, và hỗ trợ quyết định lâm sàng. Trong tài chính, AI và ML được sử dụng để phân tích dữ liệu tài chính, dự đoán xu hướng thị trường, và quản lý rủi ro.\n\nVới sự phát triển của công nghệ, AI và ML hứa hẹn mang lại nhiều cơ hội mới cho xã hội. Sự kết hợp giữa AI và ML với các công nghệ khác như blockchain, Internet of Things (IoT), và trí tuệ nhân tạo mở rộng (XAI) sẽ mở ra những tiềm năng mới trong việc tạo ra các giải pháp sáng tạo và hiệu quả cho con người.',
    image_urls: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQo_4JvYC8XrWAWm_8VVZ_gyiC5Sdz-rGJHDg&s',
      'https://nld.mediacdn.vn/2018/12/1/photo-1-15436382740761548685066.jpg',
    ],
    teacher_ids: ['8', '20'],
    language: 'english',
    created_at: new Date(new Date().setDate(new Date().getDate() - 5)),
    updated_at: new Date(),
    is_open: true,
    number_of_students: 15,
    salary: 28,
    specialized: 'Khoa học Dữ liệu và Trí tuệ nhân tạo',
    topic_ids: ['6', '7'],
    working_time: 'fulltime',
  },
  {
    id: 'cc117715-9563-4610-8590-a2434021668a',
    name: 'Công nghệ Cyber Security',
    description:
      'An toàn không gian số (Cyber Security) là lĩnh vực nghiên cứu và ứng dụng các biện pháp bảo mật để bảo vệ thông tin và dữ liệu trên mạng Internet. Với sự phát triển của công nghệ thông tin, việc bảo vệ thông tin trở nên ngày càng quan trọng và cần thiết.\n\nAn toàn không gian số bao gồm nhiều lĩnh vực khác nhau như bảo mật mạng, bảo mật ứng dụng, bảo mật dữ liệu, và bảo mật hệ thống. Các biện pháp bảo mật thông thường bao gồm mã hóa dữ liệu, kiểm tra danh tính, kiểm tra truy cập, và giám sát mạng.\n\nTrong thế giới kết nối ngày nay, an toàn không gian số đóng vai trò quan trọng trong việc bảo vệ thông tin cá nhân, doanh nghiệp, và cơ quan chính phủ khỏi các mối đe dọa mạng. Các cuộc tấn công mạng có thể gây ra thiệt hại nghiêm trọng cho các tổ chức và cá nhân, từ mất dữ liệu quan trọng đến lộ thông tin cá nhân.\n\nCông nghệ Cyber Security cũng đóng vai trò quan trọng trong việc bảo vệ hệ thống quốc gia khỏi các cuộc tấn công mạng từ các quốc gia khác. Các tổ chức chính phủ và quân đội cần có các biện pháp bảo mật mạnh mẽ để đảm bảo an ninh thông tin và truy cập vào hệ thống quốc gia.\n\nVới sự phát triển của công nghệ, an toàn không gian số sẽ tiếp tục đóng vai trò quan trọng trong việc bảo vệ thông tin và dữ liệu trên mạng Internet. Sự kết hợp giữa công nghệ Cyber Security và các công nghệ khác như trí tuệ nhân tạo (AI) và học máy (ML) sẽ mở ra những tiềm năng mới trong việc phát triển các giải pháp bảo mật tiên tiến và hiệu quả.',
    image_urls: [
      'https://d35y3h46sw2vsm.cloudfront.net/w/wp-content/uploads/2023/08/Cyber-Security.jpg',
    ],
    teacher_ids: ['9', '21'],
    created_at: new Date(new Date().setDate(new Date().getDate() - 6)),
    updated_at: new Date(),
    is_open: true,
    number_of_students: 10,
    salary: 26,
    specialized: 'An toàn không gian số - Cyber Security',
    topic_ids: ['8', '9'],
    working_time: 'parttime',
  },
  {
    id: '02a68f87-6e24-4fe7-adad-be1253b618cd',
    name: 'Công nghệ IoT và Hệ thống nhúng thông minh',
    description:
      'Internet of Things (IoT) và hệ thống nhúng thông minh là hai lĩnh vực công nghệ đang phát triển mạnh mẽ và có ứng dụng rộng rãi trong nhiều lĩnh vực khác nhau. IoT kết nối các thiết bị thông minh với nhau và với Internet, tạo ra một mạng lưới thông tin toàn cầu. Hệ thống nhúng thông minh là các hệ thống điện tử được thiết kế để thực hiện các chức năng cụ thể trong một thiết bị lớn hơn. Sự kết hợp giữa IoT và hệ thống nhúng thông minh giúp tạo ra các sản phẩm thông minh và tiện ích hơn cho cuộc sống hàng ngày.',
    image_urls: ['https://swinburne-vn.edu.vn/wp-content/uploads/image5-1.jpg'],
    teacher_ids: ['10', '22'],
    created_at: new Date(new Date().setDate(new Date().getDate() - 8)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 1)),
    is_open: true,
    number_of_students: 8,
    salary: 23,
    specialized: 'Hệ thống nhúng thông minh và IoT',
    topic_ids: ['11', '13'],
    working_time: 'fulltime',
  },
  {
    id: '02e68ba0-cac7-4cd9-99e1-84aeae162df7',
    name: 'Công nghệ 5G và Mạng di động',
    description:
      'Công nghệ 5G là một trong những công nghệ tiên tiến nhất trong lĩnh vực truyền thông di động, mang lại tốc độ truy cập Internet nhanh hơn, ổn định hơn, và đáng tin cậy hơn. 5G không chỉ cung cấp tốc độ truy cập Internet cao hơn mà còn mở ra nhiều cơ hội mới cho các ứng dụng công nghệ như trí tuệ nhân tạo (AI), Internet of Things (IoT), và xe tự hành.',
    image_urls: [
      'https://cdn.tgdd.vn/Files/2021/03/05/1332924/5g-la-gi-va-tai-sao-5g-la-cong-nghe-quan-trong-nhat-cho-tuong-lai-1.jpg',
    ],
    teacher_ids: ['11', '23'],
    created_at: new Date(new Date().setDate(new Date().getDate() - 5)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 3)),
    is_open: false,
    number_of_students: 10,
    salary: 25,
    specialized: 'Kỹ thuật Điện tử-Viễn thông',
    topic_ids: ['14', '15'],
    working_time: 'fulltime',
  },
  {
    id: '02e68ba0-cac7-4cd9-99e1-84aeae162df7',
    name: 'Công nghệ 5G và Mạng di động',
    description:
      'Công nghệ 5G là một trong những công nghệ tiên tiến nhất trong lĩnh vực truyền thông di động, mang lại tốc độ truy cập Internet nhanh hơn, ổn định hơn, và đáng tin cậy hơn. 5G không chỉ cung cấp tốc độ truy cập Internet cao hơn mà còn mở ra nhiều cơ hội mới cho các ứng dụng công nghệ như trí tuệ nhân tạo (AI), Internet of Things (IoT), và xe tự hành.',
    image_urls: [
      'https://ttcntt.hatinh.gov.vn/uploads/news/2022_06/5g.jpg',
      'https://dntech.vn/uploads/details/2020/12/images/M%E1%BA%A1ng%20di%20%C4%91%E1%BB%99ng%205G%2011.jpg',
    ],
    teacher_ids: ['11', '23'],
    language: 'japanese',
    created_at: new Date(new Date().setDate(new Date().getDate() - 12)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 5)),
    is_open: false,
    number_of_students: 10,
    salary: 25,
    specialized: 'Kỹ thuật Điện tử-Viễn thông',
    topic_ids: ['14', '15'],
    working_time: 'fulltime',
  },
  {
    id: 'a98e784f-5754-4be6-9f14-f5c4a0f3a14f',
    name: 'Nanobiotechnology Lab',
    description:
      'Lab này tập trung vào nghiên cứu và ứng dụng các công nghệ sinh học và kỹ thuật nano trong việc thiết kế và phát triển các sản phẩm và dịch vụ mới trong lĩnh vực y tế, môi trường, và nông nghiệp.',
    image_urls: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVi5oiwEOCWOrRCvj84a72GQlx858i88FLHg&s',
    ],
    teacher_ids: ['1', '2'],
    language: 'english',
    created_at: new Date(new Date().setDate(new Date().getDate() - 4)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 1)),
    is_open: true,
    number_of_students: 12,
    salary: 28,
    specialized: 'Kỹ thuật Sinh học',
    topic_ids: ['1', '2'],
    working_time: 'fulltime',
  },
  {
    id: 'bc5377c1-f9fb-4e29-8f82-f78e33db5a2d',
    name: 'Advanced Materials Chemistry Lab',
    description:
      'Lab này chuyên sâu vào nghiên cứu và phát triển các vật liệu hóa học tiên tiến, bao gồm các polymer, composite, và nanomaterials, để ứng dụng trong các lĩnh vực như y tế, năng lượng, và công nghiệp.',
    image_urls: ['https://www.eng.hokudai.ac.jp/labo/amc/img/img06.jpg'],
    teacher_ids: ['3', '4'],
    language: 'english',
    created_at: new Date(new Date().setDate(new Date().getDate() - 9)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 2)),
    is_open: true,
    number_of_students: 15,
    salary: 30,
    specialized: 'Kỹ thuật Hóa học',
    topic_ids: ['3', '4'],
    working_time: 'fulltime',
  },
  {
    id: '8eb4ac19-205e-4262-ae08-8a44de59a855',
    name: 'Educational Technology Lab',
    description:
      'Lab này tập trung vào nghiên cứu và phát triển các công nghệ và phương pháp giáo dục sáng tạo, nhằm cải thiện trải nghiệm học tập và giảng dạy trong các cấp học và môi trường học tập khác nhau.',
    image_urls: [
      'https://nazmidincer.com/assets/img/what-is-educational-technology.jpghttps://example.com/lab3.jpg',
    ],
    teacher_ids: ['5', '6'],
    language: 'english',
    created_at: new Date(new Date().setDate(new Date().getDate() - 12)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 7)),
    is_open: true,
    number_of_students: 20,
    salary: 35,
    specialized: 'Công nghệ Giáo dục',
    topic_ids: ['5', '6'],
    working_time: 'fulltime',
  },
  {
    id: 'f6ed4b26-8ec1-4a93-b82d-0f01b394cd82',
    name: 'Power Electronics and Renewable Energy Lab',
    description:
      'Lab này tập trung vào nghiên cứu và phát triển các thiết bị và hệ thống điện tử công suất cao và các nguồn năng lượng tái tạo, nhằm nâng cao hiệu suất và ổn định của hệ thống điện.',
    image_urls: [
      'https://educationaltechnology.net/wp-content/uploads/2016/10/educational-technology.png',
      'https://nazmidincer.com/assets/img/what-is-educational-technology.jpg',
    ],
    teacher_ids: ['7', '8'],
    language: 'english',
    created_at: new Date(new Date().setDate(new Date().getDate() - 7)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 5)),
    is_open: true,
    number_of_students: 18,
    salary: 32,
    specialized: 'Kỹ thuật điện',
    topic_ids: ['7', '8'],
    working_time: 'fulltime',
  },
  {
    id: '1c7b365e-4893-4fb7-8de4-918979dd6de0',
    name: 'Control Systems and Robotics Lab',
    description:
      'Lab này tập trung vào nghiên cứu và phát triển các hệ thống điều khiển tự động và robot, áp dụng trong các ứng dụng công nghiệp, y tế, và dịch vụ.',
    image_urls: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSY7YLT2tb7L0Z4s11KWfJHV9KajMAvT7WZTg&s',
    ],
    teacher_ids: ['9', '10'],
    created_at: new Date(new Date().setDate(new Date().getDate() - 2)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 1)),
    is_open: true,
    number_of_students: 15,
    salary: 30,
    specialized: 'Kỹ thuật điều khiển & Tự động hóa',
    topic_ids: ['9', '10'],
    working_time: 'fulltime',
  },
  {
    id: '3fb4f6d1-4bb2-40d5-af94-b43b3dbf5e79',
    name: 'Energy Management and Sustainable Development Lab',
    description:
      'Lab này tập trung vào nghiên cứu và phát triển các chiến lược quản lý năng lượng và các giải pháp phát triển bền vững, nhằm hỗ trợ sự phát triển kinh tế và xã hội trong điều kiện bảo vệ môi trường.',
    image_urls: [
      'https://usth.edu.vn/en/wp-content/uploads/sites/2/2018/04/12095197_1040661842613639_7086666494199395690_o-e1653296665477.jpg',
    ],
    teacher_ids: ['11', '12'],
    language: 'english',
    created_at: new Date(new Date().setDate(new Date().getDate() - 14)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 6)),
    is_open: false,
    number_of_students: 25,
    salary: 40,
    specialized: 'Quản lý Năng lượng',
    topic_ids: ['11', '12'],
    working_time: 'fulltime',
  },
  {
    id: '9139a17e-7d33-42d3-aa2a-8953e0ee4917',
    name: 'Industrial Engineering and Operations Management Lab',
    description:
      'Lab này tập trung vào nghiên cứu và phát triển các phương pháp quản lý sản xuất và vận hành hiệu quả, nhằm tối ưu hóa các quy trình và tăng cường năng suất trong môi trường công nghiệp.',
    image_urls: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4c8-SZOLV2DiNglrOlQwrgE_p1zJk3j9pxw&s',
    ],
    teacher_ids: ['13', '14'],
    language: 'english',
    created_at: new Date(new Date().setDate(new Date().getDate() - 3)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 1)),
    is_open: true,
    number_of_students: 20,
    salary: 35,
    specialized: 'Quản lý Công nghiệp',
    topic_ids: ['13', '14'],
    working_time: 'fulltime',
  },
  {
    id: 'fc9f8d69-072b-43a6-b2f4-98b9f8e8c5c3',
    name: 'Business Administration and Strategy Lab',
    description:
      'Lab này tập trung vào nghiên cứu và phát triển các chiến lược quản trị kinh doanh và phát triển doanh nghiệp, nhằm tối ưu hóa hoạt động kinh doanh và tạo ra giá trị cho cộng đồng.',
    image_urls: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8WmhJlNx3QqCRdhd3lAHcsCqSoQljDxSw6A&s',
      'https://www.slideteam.net/media/catalog/product/cache/1280x720/t/h/three_months_business_administration_strategy_roadmap_slide01.jpg',
    ],
    teacher_ids: ['15', '16'],
    language: 'english',
    created_at: new Date(new Date().setDate(new Date().getDate() - 4)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 2)),
    is_open: true,
    number_of_students: 18,
    salary: 32,
    specialized: 'Quản trị Kinh doanh',
    topic_ids: ['15', '16'],
    working_time: 'fulltime',
  },
  {
    id: '5ed18a51-dab9-47b7-90c5-aa8f635d83ff',
    name: 'Accounting and Financial Reporting Lab',
    description:
      'Lab này tập trung vào nghiên cứu và phát triển các phương pháp kế toán và báo cáo tài chính, nhằm cung cấp thông tin tài chính chính xác và minh bạch cho các doanh nghiệp và cơ quan quản lý.',
    image_urls: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgR3bYwcn9hQGkAIW5RmxapsgKDJXvvElp1w&s',
    ],
    teacher_ids: ['17', '18'],
    language: 'english',
    created_at: new Date(new Date().setDate(new Date().getDate() - 6)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 3)),
    is_open: true,
    number_of_students: 22,
    salary: 38,
    specialized: 'Kế toán',
    topic_ids: ['17', '18'],
    working_time: 'fulltime',
  },
  {
    id: '0e2a1aa3-08af-45e3-b179-d6b6b42d3e84',
    name: 'Finance and Banking LabFinance and Banking Lab',
    description:
      'Lab này tập trung vào nghiên cứu và phát triển các công nghệ và dịch vụ tài chính và ngân hàng tiên tiến, nhằm hỗ trợ quản lý tài chính cá nhân và doanh nghiệp cũng như tăng cường tính minh bạch và an toàn của hệ thống ngân hàng.',
    image_urls: [
      'https://kaplansingapore.edu.vn/wp-content/uploads/2018/03/banking-and-finance-1.jpg',
    ],
    teacher_ids: ['19', '20'],
    language: 'english',
    created_at: new Date(new Date().setDate(new Date().getDate() - 15)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 9)),
    is_open: true,
    number_of_students: 20,
    salary: 35,
    specialized: 'Tài chính-Ngân hàng',
    topic_ids: ['19', '20'],
    working_time: 'fulltime',
  },
  {
    id: '2e36de34-4b80-4e19-9d65-20d61a4d10c1',
    name: 'Electronics and Telecommunications Lab',
    description:
      'Lab này tập trung vào nghiên cứu và phát triển các thiết bị và hệ thống điện tử và viễn thông, nhằm cung cấp các dịch vụ truyền thông và kỹ thuật số hiệu quả cho các tổ chức và cá nhân.',
    image_urls: [
      'https://3.imimg.com/data3/QF/HB/MY-16673212/data-communication-laboratory.png',
    ],
    teacher_ids: ['21', '22'],
    language: 'english',
    created_at: new Date(new Date().setDate(new Date().getDate() - 8)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 2)),
    is_open: true,
    number_of_students: 18,
    salary: 32,
    specialized: 'Kỹ thuật Điện tử-Viễn thông',
    topic_ids: ['21', '22'],
    working_time: 'fulltime',
  },
  {
    id: '5e8eab9f-6af4-4477-9e4b-b52d4c74848e',
    name: 'Phòng thí nghiệm kỹ thuật y sinh',
    description:
      'Lab này tập trung vào nghiên cứu và phát triển các công nghệ và thiết bị y tế tiên tiến, nhằm cải thiện chẩn đoán, điều trị và chăm sóc sức khỏe của con người. Các dự án nghiên cứu bao gồm phát triển thiết bị y tế di động, tạo mô, và in 3D các cấu trúc sinh học.',
    image_urls: [
      'https://sbft.hust.edu.vn/wp-content/uploads/2022/06/ktys-01.png',
      'https://sbft.hust.edu.vn/wp-content/uploads/2022/06/DSC_7535.jpg',
    ],
    teacher_ids: ['23', '24'],
    language: 'japanese',
    created_at: new Date(new Date().setDate(new Date().getDate() - 8)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 6)),
    is_open: true,
    number_of_students: 15,
    salary: 30,
    specialized: 'Kỹ thuật Y sinh',
    topic_ids: ['23', '24'],
    working_time: 'fulltime',
  },
  {
    id: '4f6a897d-874d-42e8-9b97-c051b127dca1',
    name: 'Phòng thí nghiệm kỹ thuật môi trường',
    description:
      'Lab này tập trung vào nghiên cứu và phát triển các giải pháp kỹ thuật và công nghệ để bảo vệ và khôi phục môi trường, bao gồm xử lý nước, xử lý chất thải, và quản lý tài nguyên tự nhiên. Các dự án nghiên cứu tập trung vào việc phát triển các phương pháp xử lý nước hiệu quả và giảm thiểu tác động tiêu cực đến môi trường.',
    image_urls: [
      'https://example.com/lab13.jpghttps://tuyensinh.ut.edu.vn/wp-content/uploads/2023/04/image10-1.png',
    ],
    teacher_ids: ['25', '26'],
    created_at: new Date(new Date().setDate(new Date().getDate() - 8)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 2)),
    is_open: true,
    number_of_students: 20,
    salary: 35,
    specialized: 'Kỹ thuật Môi trường',
    topic_ids: ['25', '26'],
    working_time: 'fulltime',
  },
  {
    id: '1a2c42a3-2b28-4e23-a7ef-5c5e2f2985c1',
    name: 'Natural Resources and Environmental Management Lab',
    description:
      'Lab này tập trung vào nghiên cứu và phát triển các chiến lược quản lý tài nguyên tự nhiên và môi trường, nhằm bảo vệ và tối ưu hóa sử dụng tài nguyên tự nhiên cũng như giảm thiểu tác động tiêu cực đến môi trường. Các dự án nghiên cứu tập trung vào việc quản lý rừng, quản lý đất, và bảo tồn động vật hoang dã.',
    image_urls: [
      'https://cres.edu.vn/wp-content/uploads/2023/07/347445734_185889844448677_7457243090951415156_n-e1688447010205.jpg',
    ],
    teacher_ids: ['27', '28'],
    language: 'english',
    created_at: new Date(new Date().setDate(new Date().getDate() - 10)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 7)),
    is_open: true,
    number_of_students: 18,
    salary: 32,
    specialized: 'Quản lý Tài nguyên và Môi trường',
    topic_ids: ['27', '28'],
    working_time: 'fulltime',
  },
  {
    id: 'a0c4b2a8-3b17-4741-93c9-701a001d8935',
    name: 'English for Science and Technology Lab',
    description:
      'Lab này tập trung vào việc cải thiện kỹ năng Tiếng Anh cho sinh viên trong lĩnh vực Khoa học và Công nghệ. Các hoạt động học tập bao gồm học từ vựng và ngữ pháp chuyên ngành, luyện nghe và giao tiếp, cũng như viết và đọc các văn bản khoa học.',
    image_urls: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkaNdWB7_82Qy4aX1nuLJQ-VLOsqq6V72gBQ&s',
    ],
    teacher_ids: ['29', '30'],
    language: 'english',
    created_at: new Date(new Date().setDate(new Date().getDate() - 10)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 6)),
    is_open: true,
    number_of_students: 25,
    salary: 40,
    specialized: 'Tiếng Anh KHKT và Công nghệ',
    topic_ids: ['29', '30'],
    working_time: 'fulltime',
  },
  {
    id: '22e0b863-292d-4b3f-bf3e-201e99dfc96e',
    name: 'Phòng thí nghiệm Kỹ thuật Nhiệt',
    description:
      'Lab này tập trung vào nghiên cứu và phát triển các hệ thống và thiết bị liên quan đến nhiệt, bao gồm máy nén, tản nhiệt, và năng lượng nhiệt. Các dự án nghiên cứu tập trung vào tối ưu hóa hiệu suất và tiết kiệm năng lượng trong các ứng dụng công nghiệp và dân dụng.',
    image_urls: [
      'https://dut.udn.vn/Files/admin/images/Gioi_thieu/KhoaNhiet/CSVC/H03.JPG',
    ],
    teacher_ids: ['31', '32'],
    created_at: new Date(new Date().setDate(new Date().getDate() - 8)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 5)),
    is_open: true,
    number_of_students: 20,
    salary: 35,
    specialized: 'Kỹ thuật Nhiệt',
    topic_ids: ['31', '32'],
    working_time: 'fulltime',
  },
  {
    id: 'cdef0abc-b3d4-4ee6-b28a-7e31ae1fe6fd',
    name: 'Computer Engineering Lab',
    description:
      'Lab này tập trung vào nghiên cứu và phát triển các hệ thống và thiết bị phần cứng và phần mềm trong lĩnh vực công nghệ thông tin. Các dự án nghiên cứu bao gồm phát triển các vi mạch tích hợp, hệ thống nhúng, và ứng dụng IoT.',
    image_urls: [
      'https://hust.edu.vn/uploads/sys/news/2022/03/1602-news-3.112004.28859.jpg',
    ],
    teacher_ids: ['35', '36'],
    language: 'english',
    created_at: new Date(new Date().setDate(new Date().getDate() - 9)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 4)),
    is_open: true,
    number_of_students: 25,
    salary: 40,
    specialized: 'CNTT: Kỹ thuật Máy tính',
    topic_ids: ['35', '36'],
    working_time: 'fulltime',
  },
  {
    id: 'd83f1d5b-97fc-47cf-9cc5-318152fe036f',
    name: 'Electromechanical Engineering Lab',
    description:
      'Lab này tập trung vào nghiên cứu và phát triển các hệ thống và thiết bị kết hợp cả cơ và điện tử, nhằm tạo ra các giải pháp kỹ thuật toàn diện cho các ứng dụng công nghiệp và dân dụng. Các dự án nghiên cứu tập trung vào việc phát triển các thiết bị tự động hóa, robot, và máy móc thông minh.',
    image_urls: [
      'https://hust.edu.vn/uploads/sys/news/2022/03/1703-news-1.546402.28767.jpg',
    ],
    teacher_ids: ['37', '38'],
    language: 'english',
    created_at: new Date(new Date().setDate(new Date().getDate() - 7)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 4)),
    is_open: true,
    number_of_students: 20,
    salary: 35,
    specialized: 'Kỹ thuật Cơ điện tử',
    topic_ids: ['37', '38'],
    working_time: 'fulltime',
  },
  {
    id: 'b871f84b-d695-465a-9dd7-bd8196c689d9',
    name: 'Phòng thí nghiệm Cơ khí',
    description:
      'Lab này tập trung vào nghiên cứu và phát triển các hệ thống và thiết bị cơ khí, từ thiết kế đến sản xuất và vận hành. Các dự án nghiên cứu tập trung vào việc phát triển các máy móc, thiết bị vận chuyển, và các cấu trúc cơ khí phức tạp.',
    image_urls: [
      'https://sme.hust.edu.vn/wp-content/uploads/2020/11/IMG_8102-1024x683.jpg',
    ],
    teacher_ids: ['39', '40'],
    created_at: new Date(new Date().setDate(new Date().getDate() - 10)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 4)),
    is_open: true,
    number_of_students: 22,
    salary: 38,
    specialized: 'Kỹ thuật Cơ khí',
    topic_ids: ['39', '40'],
    working_time: 'fulltime',
  },
  {
    id: '1c55d951-8e56-4e8e-9a7f-1e6cc5ee01ae',
    name: 'Phòng thí nghiệm Toán học và Khoa học Máy tính',
    description:
      'Lab này tập trung vào việc áp dụng các phương pháp và công cụ toán học trong lĩnh vực công nghệ thông tin. Các dự án nghiên cứu bao gồm phát triển các thuật toán và mô hình toán học để giải quyết các vấn đề phức tạp trong khoa học máy tính và công nghệ thông tin.',
    image_urls: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBKevEzygpET_fg9MAHBaAX8UqchB_6MJczA&s',
    ],
    teacher_ids: ['41', '42'],
    created_at: new Date(new Date().setDate(new Date().getDate() - 7)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 5)),
    is_open: true,
    number_of_students: 20,
    salary: 35,
    specialized: 'Toán-Tin',
    topic_ids: ['41', '42'],
    working_time: 'fulltime',
  },
  {
    id: 'a03ac0c1-942a-463b-b2cc-6c43b04e73d6',
    name: 'Management Information Systems Lab',
    description:
      'Lab này tập trung vào nghiên cứu và phát triển các hệ thống thông tin quản lý, nhằm hỗ trợ quản lý và ra quyết định hiệu quả trong các tổ chức và doanh nghiệp. Các dự án nghiên cứu tập trung vào việc phát triển các hệ thống CRM, ERP, và Business Intelligence để cải thiện quản lý dữ liệu và thông tin.',
    image_urls: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwI_4pk9d5-iCtcmD-l3PyGohTk9jl7EqDAw&s',
    ],
    teacher_ids: ['43', '44'],
    created_at: new Date(new Date().setDate(new Date().getDate() - 7)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 6)),
    is_open: true,
    number_of_students: 25,
    salary: 40,
    specialized: 'Hệ thống Thông tin quản lý',
    topic_ids: ['43', '44'],
    working_time: 'fulltime',
  },
  {
    id: '9f29604a-0f48-45cb-b5a0-0705f2ba3ad9',
    name: 'Phòng thí nghiệm Kỹ thuật Vật liệu',
    description:
      'Lab này tập trung vào nghiên cứu và phát triển các vật liệu mới và tiên tiến, nhằm cải thiện hiệu suất và tính năng của sản phẩm và quy trình công nghệ. Các dự án nghiên cứu tập trung vào việc phát triển các vật liệu nano, vật liệu siêu nhẹ và siêu cứng, và vật liệu chống ăn mòn.',
    image_urls: [
      'https://sep.hust.edu.vn/wp-content/uploads/PhysicsLab-400x300.jpg',
    ],
    teacher_ids: ['45', '46'],
    created_at: new Date(new Date().setDate(new Date().getDate() - 7)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 1)),
    is_open: true,
    number_of_students: 20,
    salary: 35,
    specialized: 'Kỹ thuật Vật liệu',
    topic_ids: ['45', '46'],
    working_time: 'fulltime',
  },
  {
    id: '6d0d7c4a-cc82-4cd5-a632-6c0dbcb798e8',
    name: 'Polymer and Composite Materials Technology Lab',
    description:
      'Lab này tập trung vào nghiên cứu và phát triển các vật liệu polymer và composite, nhằm cải thiện tính năng và hiệu suất của các sản phẩm trong các ngành công nghiệp đa dạng như ô tô, hàng không, và y tế. Các dự án nghiên cứu tập trung vào việc phát triển các vật liệu nhẹ, cứng, và bền vững môi trường.',
    image_urls: [
      'https://ts.hust.edu.vn/storage/app/public/trainings/September2023/Polyme_02.jpg',
    ],
    teacher_ids: ['49', '50'],
    created_at: new Date(new Date().setDate(new Date().getDate() - 7)),
    updated_at: new Date(new Date().setDate(new Date().getDate() - 3)),
    is_open: true,
    number_of_students: 22,
    salary: 38,
    specialized: 'Công nghệ vật liệu Polyme và Compozit',
    topic_ids: ['49', '50'],
    working_time: 'fulltime',
  },
];
