import type { LabTopics } from '.';

export const LabTopicsData: LabTopics[] = [
  {
    id: '1',
    name: 'Nghiên cứu về tơ',
    description:
      'Nghiên cứu về tơ là nơi đào tạo các kỹ sư in ấn chuyên nghiệp',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '1',
  },
  {
    id: '2',
    name: 'Xây dựng mô hình dự đoán giá nhà',
    description: 'Nghiên cứu xây dựng mô hình dự đoán giá bất động sản Hà Nội',
    number_of_students: 5,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '2',
  },
  {
    id: '3',
    name: 'Tạo bản vẽ chip',
    description: 'Thiết kế vẽ chip cho công ty Nvidia',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '4',
  },
  {
    id: '4',
    name: 'Web Blockchain',
    description: 'Viết web demo cho hệ thống blockchain',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '3',
  },
  {
    id: '5',
    name: 'Phân tích y sinh',
    description: 'Phân tích dự liệu x-quang bênh viện Bạch Mai',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '1',
  },
  {
    id: '6',
    name: 'Dự đoán thời tiết',
    description: 'Xây dựng mô hình dự đoán lượng mưa ở Việt Nam',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '5',
  },
  {
    id: '7',
    name: 'Phân loại nội dung',
    description: 'Phân loại bình luận trên FB của trường',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '6',
  },
  {
    id: '8',
    name: 'Xây dựng web thi cử',
    description: 'Xây dựng web phục vụ thi lập trình ở trường',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '7',
  },
  {
    id: '9',
    name: 'Nghiên cứu về tơ',
    description:
      'Nghiên cứu về tơ là nơi đào tạo các kỹ sư in ấn chuyên nghiệp',
    number_of_students: 5,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '8',
  },
  {
    id: '10',
    name: 'Sinh giọng nói',
    description: 'Sinh giọng nói tiếng Việt tự nhiên',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '9',
  },
  {
    id: '11',
    name: 'AI trong chẩn đoán u',
    description:
      'Nghiên cứu ứng dụng AI trong phân tích và chẩn đoán khối u từ hình ảnh y khoa.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '10',
  },
  {
    id: '12',
    name: 'Nghiên cứu về web3',
    description: 'Nghiên cứu về đặc điểm công nghệ web3',
    number_of_students: 4,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '11',
  },
  {
    id: '13',
    name: 'Trí tuệ nhân tạo trong chẩn đoán y khoa',
    description:
      'Nghiên cứu ứng dụng AI trong phân tích và chẩn đoán bệnh từ hình ảnh y khoa.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '12',
  },
  {
    id: '14',
    name: 'Học máy trong phân tích dữ liệu lớn',
    description:
      'Phát triển thuật toán học máy để xử lý và phân tích dữ liệu lớn.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '13',
  },
  {
    id: '15',
    name: 'An ninh mạng cho hệ thống IoT',
    description:
      'Khảo sát các phương pháp bảo vệ và tăng cường an ninh cho các thiết bị IoT.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '14',
  },
  {
    id: '16',
    name: 'Blockchain trong quản lý chuỗi cung ứng',
    description:
      'Ứng dụng công nghệ blockchain để theo dõi và quản lý chuỗi cung ứng.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '15',
  },
  {
    id: '17',
    name: 'Xử lý ngôn ngữ tự nhiên trong chatbots',
    description:
      'Phát triển chatbot thông minh có khả năng hiểu và phản hồi ngôn ngữ tự nhiên.',
    number_of_students: 5,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '16',
  },
  {
    id: '18',
    name: 'Phân tích dữ liệu cảm biến trong nông nghiệp',
    description:
      'Sử dụng dữ liệu từ cảm biến để cải thiện quy trình nông nghiệp.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '17',
  },
  {
    id: '19',
    name: 'Mạng nơ-ron sâu cho nhận diện hình ảnh',
    description:
      'Nghiên cứu các mô hình mạng nơ-ron sâu để nhận diện và phân loại hình ảnh.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '18',
  },
  {
    id: '20',
    name: 'Điện toán biên cho các ứng dụng IoT',
    description:
      'Phân tích lợi ích và thách thức của việc sử dụng điện toán biên trong các hệ thống IoT.',
    number_of_students: 4,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '19',
  },
  {
    id: '21',
    name: 'Thực tế ảo tăng cường trong giáo dục',
    description: 'Khảo sát việc sử dụng AR để nâng cao trải nghiệm học tập.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '20',
  },
  {
    id: '22',
    name: 'Tối ưu hóa hiệu suất hệ thống máy chủ',
    description:
      'Phát triển các giải pháp để tối ưu hóa hiệu suất và tiết kiệm năng lượng cho hệ thống máy chủ.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '21',
  },
  {
    id: '23',
    name: 'AI trong phát hiện gian lận tài chính',
    description:
      'Ứng dụng AI để phát hiện các hành vi gian lận trong lĩnh vực tài chính.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '22',
  },
  {
    id: '24',
    name: 'Công nghệ 5G và tương lai kết nối mạng',
    description:
      'Nghiên cứu tiềm năng và ứng dụng của công nghệ 5G trong việc kết nối mạng.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '23',
  },
  {
    id: '25',
    name: 'Quản lý tài nguyên điện toán đám mây',
    description:
      'Phát triển các phương pháp quản lý và tối ưu hóa tài nguyên trong môi trường điện toán đám mây',
    number_of_students: 4,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '24',
  },
  {
    id: '26',
    name: 'Học sâu trong phân tích thị giác máy tính',
    description:
      'Ứng dụng học sâu để cải thiện khả năng phân tích hình ảnh và video.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '25',
  },
  {
    id: '27',
    name: 'Ứng dụng AI trong y tế cá nhân hóa',
    description:
      'Nghiên cứu các hệ thống AI hỗ trợ y tế dựa trên dữ liệu cá nhân hóa.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '26',
  },
  {
    id: '28',
    name: 'Bảo mật dữ liệu trong điện toán đám mây',
    description:
      'Phát triển các phương pháp bảo mật để bảo vệ dữ liệu trong môi trường đám mây.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '27',
  },
  {
    id: '29',
    name: 'Phát triển phần mềm dựa trên microservices',
    description:
      'Khảo sát các phương pháp và lợi ích của kiến trúc microservices trong phát triển phần mềm.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '28',
  },
  {
    id: '30',
    name: 'Blockchain trong bảo mật thông tin',
    description:
      'Ứng dụng công nghệ blockchain để tăng cường bảo mật thông tin.',
    number_of_students: 5,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '29',
  },
  {
    id: '31',
    name: 'Tự động hóa quy trình nghiệp vụ bằng RPA',
    description:
      'Nghiên cứu ứng dụng Robotic Process Automation để tự động hóa các quy trình kinh doanh',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '30',
  },
  {
    id: '32',
    name: 'AI trong hệ thống giao thông thông minh',
    description:
      'Phát triển các hệ thống giao thông thông minh sử dụng AI để quản lý và điều phối giao thông.',
    number_of_students: 4,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '31',
  },
  {
    id: '33',
    name: 'Phân tích và dự báo thời tiết bằng AI',
    description:
      'Ứng dụng AI để phân tích dữ liệu khí tượng và dự báo thời tiết chính xác hơn.',
    number_of_students: 4,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '32',
  },
  {
    id: '34',
    name: 'Nhận dạng giọng nói và ứng dụng',
    description:
      'Nghiên cứu các công nghệ nhận dạng giọng nói và ứng dụng trong các lĩnh vực khác nhau.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '33',
  },
  {
    id: '35',
    name: 'Điện toán lượng tử và bảo mật dữ liệu',
    description:
      'Khảo sát tiềm năng của điện toán lượng tử trong việc bảo mật dữ liệu.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '34',
  },
  {
    id: '36',
    name: 'Hệ thống quản lý học tập trực tuyến',
    description:
      'hát triển và tối ưu hóa các hệ thống quản lý học tập trực tuyến.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '35',
  },
  {
    id: '37',
    name: 'Ứng dụng AI trong phân tích hành vi người dùng',
    description:
      'Nghiên cứu các phương pháp sử dụng AI để phân tích hành vi người dùng trên mạng.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '36',
  },
  {
    id: '38',
    name: 'Mạng nơ-ron tái phát trong xử lý ngôn ngữ tự nhiên',
    description: 'Ứng dụng RNN để phân tích và xử lý ngôn ngữ tự nhiên.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '37',
  },
  {
    id: '39',
    name: 'Công nghệ sinh trắc học trong bảo mật thông tin',
    description:
      'Nghiên cứu các phương pháp sinh trắc học để bảo vệ thông tin và xác thực người dùng.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '38',
  },
  {
    id: '40',
    name: 'AI trong tối ưu hóa quy trình sản xuất',
    description:
      'Ứng dụng AI để tối ưu hóa các quy trình sản xuất công nghiệp.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '39',
  },
  {
    id: '41',
    name: 'Phân tích dữ liệu lớn về y tế',
    description:
      'Khảo sát các phương pháp và công cụ phân tích dữ liệu lớn về y tế để cải thiện chăm sóc sức khỏe.',
    number_of_students: 4,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '40',
  },
  {
    id: '42',
    name: 'Blockchain và tiền điện tử',
    description:
      'Nghiên cứu các ứng dụng và tiềm năng của blockchain và tiền điện tử trong kinh tế số.',
    number_of_students: 5,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '41',
  },
  {
    id: '43',
    name: 'Hệ thống AI cho điều khiển robot tự động',
    description:
      'Phát triển hệ thống AI để điều khiển và vận hành robot tự động.',
    number_of_students: 6,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '42',
  },
  {
    id: '44',
    name: 'Công nghệ không dây thế hệ mới',
    description:
      'Nghiên cứu và phát triển các công nghệ không dây thế hệ mới như Wi-Fi 6 và 6G.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '43',
  },
  {
    id: '45',
    name: 'Ứng dụng AI trong thương mại điện tử',
    description:
      'Nghiên cứu các phương pháp sử dụng AI để cải thiện trải nghiệm mua sắm trực tuyến.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '44',
  },
  {
    id: '46',
    name: 'Phát triển ứng dụng di động đa nền tảng',
    description:
      'Khảo sát các công cụ và phương pháp phát triển ứng dụng di động trên nhiều nền tảng.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '45',
  },
  {
    id: '47',
    name: 'AI trong phân tích video giám sát',
    description:
      'Ứng dụng AI để phân tích và nhận diện các hành vi bất thường trong video giám sát.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '46',
  },
  {
    id: '48',
    name: 'Tối ưu hóa công cụ tìm kiếm bằng AI',
    description:
      'Phát triển các thuật toán AI để cải thiện kết quả tìm kiếm trực tuyến.',
    number_of_students: 5,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '47',
  },
  {
    id: '49',
    name: 'Hệ thống AI hỗ trợ quyết định trong kinh doanh',
    description:
      'Nghiên cứu các hệ thống AI để hỗ trợ ra quyết định trong quản lý kinh doanh.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '48',
  },
  {
    id: '50',
    name: 'Ứng dụng học sâu trong y học chính xác',
    description:
      'Nghiên cứu ứng dụng học sâu để cá nhân hóa các phương pháp điều trị y tế.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '49',
  },
  {
    id: '51',
    name: 'Bảo mật và riêng tư trong mạng xã hội',
    description:
      'Khảo sát các phương pháp bảo vệ bảo mật và quyền riêng tư trên mạng xã hội.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '50',
  },
  {
    id: '52',
    name: 'Hệ thống đề xuất sản phẩm dựa trên AI',
    description:
      'Phát triển các hệ thống đề xuất sản phẩm sử dụng AI để cá nhân hóa trải nghiệm người dùng.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '51',
  },
  {
    id: '53',
    name: 'Phân tích dữ liệu thị trường tài chính bằng AI',
    description:
      'Ứng dụng AI để phân tích và dự đoán xu hướng thị trường tài chính.',
    number_of_students: 4,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '52',
  },
  {
    id: '54',
    name: 'Quản lý và bảo vệ dữ liệu trong hệ thống y tế',
    description: 'Nghiên cứu các phương pháp quản lý và bảo vệ dữ liệu y tế.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '53',
  },
  {
    id: '55',
    name: 'Ứng dụng AI trong chăm sóc sức khỏe tâm lý',
    description:
      'Phát triển các hệ thống AI hỗ trợ chăm sóc và điều trị sức khỏe tâm lý.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '54',
  },
  {
    id: '56',
    name: 'Điện toán đám mây cho giáo dục trực tuyến',
    description:
      'Khảo sát các lợi ích và thách thức của việc sử dụng điện toán đám mây trong giáo dục trực tuyến.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '55',
  },
  {
    id: '57',
    name: 'AI trong tự động hóa công nghiệp',
    description:
      'Nghiên cứu các phương pháp sử dụng AI để tự động hóa quy trình sản xuất công nghiệp.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '56',
  },
  {
    id: '58',
    name: 'Bảo mật hệ thống thanh toán trực tuyến',
    description:
      'Phát triển các giải pháp bảo mật để bảo vệ hệ thống thanh toán trực tuyến.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '57',
  },
  {
    id: '59',
    name: 'Phát triển trò chơi điện tử bằng AI',
    description:
      'Ứng dụng AI để phát triển và cải thiện trải nghiệm chơi game.',
    number_of_students: 4,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '58',
  },
  {
    id: '60',
    name: 'Quản lý và phân tích dữ liệu sinh học',
    description:
      'Nghiên cứu các công cụ và phương pháp quản lý dữ liệu sinh học.',
    number_of_students: 4,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '59',
  },
  {
    id: '61',
    name: 'AI trong mạng xã hội',
    description: 'Nghiên cứu về tác động của AI đến người dùng mạng xã hội',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '60',
  },
  {
    id: '62',
    name: 'AI trong phát triển đô thị thông minh',
    description:
      'Ứng dụng AI để quản lý và phát triển các thành phố thông minh.',
    number_of_students: 5,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '61',
  },
  {
    id: '63',
    name: 'Tối ưu hóa mạng lưới điện bằng AI',
    description:
      'Phát triển các thuật toán AI để tối ưu hóa vận hành mạng lưới điện.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '62',
  },
  {
    id: '64',
    name: 'Phát triển hệ thống phát hiện xâm nhập mạng',
    description:
      'Nghiên cứu các phương pháp phát hiện và ngăn chặn xâm nhập mạng.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '63',
  },
  {
    id: '65',
    name: 'Bảo mật hệ thống học sâu',
    description: 'Nghiên cứu về bảo mật mô hình trong hệ thống học sâu.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '64',
  },
  {
    id: '66',
    name: 'Công nghệ AI trong tối ưu hóa logistics',
    description:
      'Ứng dụng AI để tối ưu hóa quy trình logistics và quản lý kho hàng.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '65',
  },
  {
    id: '67',
    name: 'Ứng dụng AI trong chăm sóc sức khỏe từ xa',
    description: 'Phát triển các hệ thống AI hỗ trợ chăm sóc sức khỏe từ xa.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '66',
  },
  {
    id: '68',
    name: 'Điện toán đám mây cho doanh nghiệp nhỏ và vừa',
    description:
      'Khảo sát lợi ích và thách thức của việc áp dụng điện toán đám mây cho SMEs.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '67',
  },
  {
    id: '69',
    name: 'Hệ thống AI dự đoán nhu cầu thị trường',
    description:
      'Nghiên cứu các hệ thống AI để dự đoán nhu cầu thị trường và quản lý tồn kho.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '68',
  },
  {
    id: '70',
    name: 'AI trong quản lý tài sản công ty',
    description:
      'Phát triển các giải pháp AI để quản lý và tối ưu hóa tài sản công ty.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '69',
  },
  {
    id: '71',
    name: 'Bảo mật thông tin trong hệ thống viễn thông',
    description:
      'Nghiên cứu các phương pháp bảo mật thông tin trong hệ thống viễn thông.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '70',
  },
  {
    id: '72',
    name: 'Ứng dụng học máy trong quảng cáo trực tuyến',
    description:
      'Phát triển các thuật toán học máy để tối ưu hóa chiến dịch quảng cáo trực tuyến.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '2',
  },
  {
    id: '73',
    name: 'Hệ thống nhận dạng khuôn mặt bằng AI',
    description:
      'Nghiên cứu và phát triển hệ thống nhận dạng khuôn mặt sử dụng AI.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '4',
  },
  {
    id: '74',
    name: 'AI trong phân tích dữ liệu thị trường bất động sản',
    description:
      'Ứng dụng AI để phân tích và dự đoán xu hướng thị trường bất động sản.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '6',
  },
  {
    id: '75',
    name: 'Phát triển ứng dụng y tế di động',
    description:
      'Nghiên cứu các phương pháp phát triển ứng dụng di động hỗ trợ y tế và chăm sóc sức khỏe.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '8',
  },
  {
    id: '76',
    name: 'Công nghệ AI trong sản xuất ô tô tự lái',
    description:
      'Ứng dụng AI để phát triển các hệ thống điều khiển ô tô tự lái.',
    number_of_students: 5,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '10',
  },
  {
    id: '77',
    name: 'Học sâu trong phân tích dữ liệu âm thanh',
    description:
      'Nghiên cứu các mô hình học sâu để phân tích và nhận diện âm thanh.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '12',
  },
  {
    id: '78',
    name: 'Phân tích hành vi người dùng trên mạng xã hội',
    description:
      'Nử dụng AI để phân tích và dự đoán hành vi người dùng trên mạng xã hội.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '14',
  },
  {
    id: '79',
    name: 'Ứng dụng học sâu trong phân tích dữ liệu gen',
    description:
      'Nghiên cứu ứng dụng học sâu để phân tích và giải mã dữ liệu gen.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '16',
  },
  {
    id: '80',
    name: 'Tối ưu hóa quy trình sản xuất bằng AI',
    description:
      'Phát triển các giải pháp AI để tối ưu hóa quy trình sản xuất và giảm thiểu chi phí.',
    number_of_students: 5,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '18',
  },
  {
    id: '81',
    name: 'AI trong phát hiện và điều trị ung thư',
    description:
      'Ứng dụng AI để phát hiện sớm và cá nhân hóa phương pháp điều trị ung thư.',
    number_of_students: 4,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '20',
  },
  {
    id: '82',
    name: 'Hệ thống AI hỗ trợ chăm sóc người già',
    description:
      'Phát triển các hệ thống AI hỗ trợ chăm sóc và giám sát sức khỏe người già.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '22',
  },
  {
    id: '83',
    name: 'Blockchain trong quản lý dữ liệu y tế',
    description:
      'Ứng dụng blockchain để bảo vệ và quản lý dữ liệu y tế một cách an toàn.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '24',
  },
  {
    id: '84',
    name: 'Phát triển ứng dụng học tiếng Anh bằng AI',
    description:
      'Nghiên cứu các phương pháp sử dụng AI để phát triển ứng dụng học tiếng Anh.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '26',
  },
  {
    id: '85',
    name: 'Tối ưu hóa mạng truyền thông bằng AI',
    description:
      'Phát triển các thuật toán AI để tối ưu hóa hiệu suất và bảo mật mạng truyền thông.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '28',
  },
  {
    id: '86',
    name: 'Hệ thống AI dự đoán khủng hoảng tài chính',
    description:
      'Nghiên cứu các hệ thống AI để dự đoán và phòng ngừa khủng hoảng tài chính.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '30',
  },
  {
    id: '87',
    name: 'Ứng dụng AI trong kiểm tra chất lượng sản phẩm',
    description:
      'Phát triển các hệ thống AI để kiểm tra và đảm bảo chất lượng sản phẩm.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '32',
  },
  {
    id: '88',
    name: 'Công nghệ không dây cho các thiết bị IoT',
    description:
      'Nghiên cứu và phát triển các công nghệ không dây hỗ trợ thiết bị IoT.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '34',
  },
  {
    id: '89',
    name: 'AI trong phân tích dữ liệu người tiêu dùng',
    description:
      'Ứng dụng AI để phân tích và dự đoán xu hướng hành vi người tiêu dùng.',
    number_of_students: 4,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '36',
  },
  {
    id: '90',
    name: 'Hệ thống AI hỗ trợ học tập cá nhân hóa',
    description:
      'Phát triển các hệ thống AI để hỗ trợ học tập và giáo dục cá nhân hóa.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '38',
  },
  {
    id: '91',
    name: 'Blockchain và hợp đồng thông minh',
    description:
      'Nghiên cứu ứng dụng hợp đồng thông minh trong các giao dịch kinh tế và pháp lý.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '40',
  },
  {
    id: '92',
    name: 'Ứng dụng học máy trong tối ưu hóa năng lượng',
    description:
      'Phát triển các thuật toán học máy để tối ưu hóa sử dụng năng lượng trong các hệ thống công nghiệp.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '42',
  },
  {
    id: '93',
    name: 'AI trong quản lý môi trường và tài nguyên',
    description:
      'Ứng dụng AI để quản lý và bảo vệ môi trường và tài nguyên thiên nhiên.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '44',
  },
  {
    id: '94',
    name: 'Phát triển hệ thống hỗ trợ tư vấn pháp lý bằng AI',
    description:
      'Nghiên cứu và phát triển các hệ thống AI hỗ trợ tư vấn pháp lý.',
    number_of_students: 4,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '46',
  },
  {
    id: '95',
    name: 'AI trong dự báo và quản lý thiên tai',
    description: 'Ứng dụng AI để dự báo và quản lý rủi ro thiên tai.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '48',
  },
  {
    id: '96',
    name: 'Hệ thống AI hỗ trợ điều trị bệnh mãn tính',
    description:
      'Phát triển các hệ thống AI hỗ trợ điều trị và quản lý bệnh mãn tính.',
    number_of_students: 5,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '50',
  },
  {
    id: '97',
    name: 'Ứng dụng học sâu trong phân tích dữ liệu thời trang',
    description:
      'Nghiên cứu ứng dụng học sâu để phân tích xu hướng và dự đoán thị trường thời trang.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '52',
  },
  {
    id: '98',
    name: 'AI trong tối ưu hóa hệ thống năng lượng tái tạo',
    description:
      'Phát triển các giải pháp AI để tối ưu hóa hiệu suất hệ thống năng lượng tái tạo.',
    number_of_students: 4,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '54',
  },
  {
    id: '99',
    name: 'Hệ thống AI hỗ trợ chăm sóc trẻ em',
    description:
      'Nghiên cứu và phát triển các hệ thống AI hỗ trợ chăm sóc và giám sát trẻ em.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '56',
  },
  {
    id: '100',
    name: 'Ứng dụng blockchain trong quản lý tài sản số',
    description:
      'Khảo sát ứng dụng blockchain để quản lý và bảo vệ tài sản số.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '58',
  },
  {
    id: '101',
    name: 'AI trong phát hiện và ngăn chặn tấn công mạng',
    description:
      'Phát triển các hệ thống AI để phát hiện và ngăn chặn tấn công mạng.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '60',
  },
  {
    id: '102',
    name: 'Ứng dụng học máy trong phân tích dữ liệu y tế',
    description:
      'Nghiên cứu các thuật toán học máy để phân tích dữ liệu y tế và hỗ trợ quyết định y khoa.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '62',
  },
  {
    id: '103',
    name: 'Hệ thống AI hỗ trợ quản lý tài chính cá nhân',
    description:
      'Phát triển các hệ thống AI hỗ trợ quản lý và tối ưu hóa tài chính cá nhân.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '64',
  },
  {
    id: '104',
    name: 'AI trong phân tích và dự đoán thị trường chứng khoán',
    description:
      'Ứng dụng AI để phân tích và dự đoán biến động thị trường chứng khoán.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '66',
  },
  {
    id: '105',
    name: 'Phát triển ứng dụng AI hỗ trợ tìm kiếm việc làm',
    description:
      'Nghiên cứu các phương pháp sử dụng AI để phát triển ứng dụng hỗ trợ tìm kiếm việc làm.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '68',
  },
  {
    id: '106',
    name: 'AI trong tối ưu hóa quản lý dự án',
    description:
      'Phát triển các hệ thống AI để tối ưu hóa quy trình và hiệu quả quản lý dự án.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '70',
  },
  {
    id: '107',
    name: 'Ứng dụng học sâu trong phân tích dữ liệu thời tiết',
    description:
      'Nghiên cứu ứng dụng học sâu để phân tích và dự báo thời tiết.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '5',
  },
  {
    id: '108',
    name: 'AI trong quản lý và bảo vệ hệ sinh thái',
    description:
      'Phát triển các giải pháp AI để quản lý và bảo vệ hệ sinh thái tự nhiên.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '15',
  },
  {
    id: '109',
    name: 'Hệ thống AI hỗ trợ quản lý nhà hàng và khách sạn',
    description:
      'Nghiên cứu và phát triển các hệ thống AI hỗ trợ quản lý và tối ưu hóa hoạt động nhà hàng và khách sạn.',
    number_of_students: 1,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '25',
  },
  {
    id: '110',
    name: 'Ứng dụng blockchain trong quản lý chuỗi cung ứng thực phẩm',
    description:
      'Khảo sát ứng dụng blockchain để theo dõi và quản lý chuỗi cung ứng thực phẩm.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '35',
  },
  {
    id: '111',
    name: 'AI trong quản lý và phát triển nguồn nhân lực',
    description:
      'Phát triển các hệ thống AI để quản lý và phát triển nguồn nhân lực hiệu quả.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '45',
  },
  {
    id: '112',
    name: 'Học sâu trong phân tích dữ liệu y học hình ảnh',
    description:
      'Nghiên cứu các mô hình học sâu để phân tích và chẩn đoán từ dữ liệu y học hình ảnh.',
    number_of_students: 4,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '55',
  },
  {
    id: '113',
    name: 'AI trong phát hiện và phòng ngừa tội phạm',
    description: 'Ứng dụng AI để phát hiện và ngăn chặn các hành vi tội phạm.',
    number_of_students: 3,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '65',
  },
  {
    id: '114',
    name: 'Phát triển hệ thống AI hỗ trợ học ngoại ngữ',
    description:
      'Nghiên cứu và phát triển các hệ thống AI hỗ trợ học và nâng cao kỹ năng ngoại ngữ.',
    number_of_students: 2,
    created_at: new Date(),
    updated_at: new Date(),
    teacher_id: '39',
  },
];
