import type { Teacher } from '.';

export const TeacherData: Teacher[] = [
  {
    id: 'wzoCkgV',
    name: 'Nguyen Bao Phuong',
    email: 'BPhuong@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0005273933',
  },
  {
    id: 'eDgUzvz',
    name: 'Ho Kim Binh',
    email: 'KBinh@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0280286781',
  },
  {
    id: 'MUqlzEn',
    name: 'Ho Gia Phu',
    email: 'GPhu@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0182754393',
  },
  {
    id: 'qalUSTX',
    name: 'Pham Hong Yen',
    email: 'yen@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0996043767',
  },
  {
    id: 'ttJrRiK',
    name: 'Phan Van Binh',
    email: 'binh@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0760062728',
  },
  {
    id: 'WuoeixS',
    name: 'Phan Van Ngoc',
    email: 'ngoc@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0993311244',
  },
  {
    id: 'Eiroksn',
    name: 'Le Ngoc Phuong',
    email: 'Phuong@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0998502754',
  },
  {
    id: 'zEICoTt',
    name: 'Pham Gia Thu',
    email: 'Thu@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0957495638',
  },
  {
    id: 'FaJECkl',
    name: 'Vo Hong Tuan',
    email: 'Tuan@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0985614225',
  },
  {
    id: 'IxQYRiR',
    name: 'Duong Hong Dung',
    email: 'Dung@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0967088553',
  },
  {
    id: 'RssmilJ',
    name: 'Nguyễn Văn Tung',
    email: 'TungNV@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0946802461',
  },
  {
    id: 'zvoGVAJ',
    name: 'Tran Huu Lam',
    email: 'LamHT@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0246686847',
  },
  {
    id: 'NKKYXlv',
    name: 'Vu Minh Hieu',
    email: 'HieuVH@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0401483748',
  },
  {
    id: 'fwqsHOA',
    name: 'Vu The Long',
    email: 'LongVT@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0295780135',
  },
  {
    id: 'CSXWcBg',
    name: 'Pham Gia Tuan',
    email: 'tuanPG@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0194659952',
  },
];
