import type { Teacher } from '.';

export const TeacherData: Teacher[] = [
  {
    id: 'wzoCkgV',
    name: 'Nguyen Bao Phuong',
    email: 'BPhuong@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0005273933',
  },
  {
    id: 'eDgUzvz',
    name: 'Ho Kim Binh',
    email: 'KBinh@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0280286781',
  },
  {
    id: 'nZLZpPl',
    name: 'Ho Gia Phu',
    email: 'GPhu@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0182754393',
  },
  {
    id: 'svyGNxs',
    name: 'Pham Hong Yen',
    email: 'yen@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0996043767',
  },
  {
    id: 'nZLZpPl',
    name: 'Phan Van Binh',
    email: 'binh@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0760062728',
  },
  {
    id: 'WuoeixS',
    name: 'Phan Van Ngoc',
    email: 'ngoc@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0993311244',
  },
  {
    id: 'Eiroksn',
    name: 'Le Ngoc Phuong',
    email: 'Phuong@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0998502754',
  },
  {
    id: 'zEICoTt',
    name: 'Pham Gia Thu',
    email: 'Thu@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0957495638',
  },
  {
    id: 'FaJECkl',
    name: 'Vo Hong Tuan',
    email: 'Tuan@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0985614225',
  },
  {
    id: 'IxQYRiR',
    name: 'Duong Hong Dung',
    email: 'Dung@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0967088553',
  },
  {
    id: 'RssmilJ',
    name: 'Nguyễn Văn Tung',
    email: 'TungNV@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0946802461',
  },
  {
    id: 'zvoGVAJ',
    name: 'Tran Huu Lam',
    email: 'LamHT@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0246686847',
  },
  {
    id: 'NKKYXlv',
    name: 'Vu Minh Hieu',
    email: 'HieuVH@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0401483748',
  },
  {
    id: 'fwqsHOA',
    name: 'Vu The Long',
    email: 'LongVT@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0295780135',
  },
  {
    id: 'CSXWcBg',
    name: 'Pham Gia Tuan',
    email: 'tuanPG@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0194659952',
  },
  {
    id: 'YQIYjVp',
    name: 'Ly Hong Quoc',
    email: 'QuocLy@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0005273933',
  },
  {
    id: 'YojJAgp',
    name: 'Huynh Van Lam',
    email: 'lamhuynh@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0098913016',
  },
  {
    id: 'fLioQaV',
    name: 'Tran Thi Minh',
    email: 'GPhu@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0317203621',
  },
  {
    id: 'JaedLdB',
    name: 'Vo Bao Vy',
    email: 'VY@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0609955694',
  },
  {
    id: 'TPHAlsp',
    name: 'Dang Ngoc Ha',
    email: 'Ha@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0305876258',
  },
  {
    id: 'EotibRu',
    name: 'Huynh Kim Phuong',
    email: 'PhuongHynh@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0981483418',
  },
  {
    id: 'IbnkYvv',
    name: 'Hoang Thi Phuong',
    email: 'HPhuong@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0465517472',
  },
  {
    id: 'PUnKhLs',
    name: 'Pham Gia Mai',
    email: 'Mai@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0590977309',
  },
  {
    id: 'bliBmAL',
    name: 'Vo Huu Thuy',
    email: 'Thuy@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0557473046',
  },
  {
    id: 'GHMssSF',
    name: 'Hoang Huu Vy',
    email: 'Vyhoang@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0011339419',
  },
  {
    id: 'eyvuhzi',
    name: 'Vo Bao Cuong',
    email: 'Cuong@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0300094400',
  },
  {
    id: 'xbJuhpu',
    name: 'Pham Van Huong',
    email: 'Huong@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0214561343',
  },
  {
    id: 'ircGHHQ',
    name: 'Huynh Thi Vi',
    email: 'ViVH@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0521563149',
  },
  {
    id: 'ALbveYV',
    name: 'Nguyen Hong Thanh',
    email: 'ThanhHong@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0291906955',
  },
  {
    id: 'cSDdteN',
    name: 'Pham The Tuan',
    email: 'tuanP@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0751239879',
  }, {
    id: 'BkGeanD',
    name: 'Phan Kim Son',
    email: 'SonPK@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0554264533',
  },
  {
    id: 'tQVHydK',
    name: 'Ho Kim Duong',
    email: 'Duong@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0479508307',
  },
  {
    id: 'NkawAiT',
    name: 'Duong Xuan Chau',
    email: 'XuanCha@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0425111320',
  },
  {
    id: 'JIIKdsO',
    name: 'Pham Hong Van',
    email: 'Van08@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0329782982',
  },
  {
    id: 'RsUfOGs',
    name: 'Phan Van Phuc',
    email: 'Phuc@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '"0155927133',
  },
  {
    id: 'JIIKdsO',
    name: 'Phan Van Dong',
    email: 'dong09@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0996488343',
  },
  {
    id: 'mDVXNpI',
    name: 'Le Ngoc Hung',
    email: 'HungLE@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0763697520',
  },
  {
    id: 'ViWgyDJ',
    name: 'Pham Gia Truong',
    email: 'Truong@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0916289232',
  },
  {
    id: 'ujbKAdG',
    name: 'Vo Hong Chau',
    email: 'Chau@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0355620816',
  },
  {
    id: 'tGFfSHs',
    name: 'Duong Hong Nhat',
    email: 'Nhat09@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '044250493',
  },
  {
    id: 'BnYlQow',
    name: 'Nguyễn Văn Truong',
    email: 'TruongNg@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0946802461',
  },
  {
    id: 'zvoGVAJ',
    name: 'Tran Huu Lam',
    email: 'LamHT@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0894425049',
  },
  {
    id: 'uUscYpm',
    name: 'Vu Minh Hien',
    email: 'HienVH@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0300374300',
  },
  {
    id: 'IxWzMaq',
    name: 'Vu The Hung',
    email: 'HungVT@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0059800522',
  },
  {
    id: 'wOdSKrw',
    name: 'Pham Gia Hung',
    email: 'hungPG@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0 144755108',
  }, {
    id: 'wzoCkgV',
    name: 'Nguyen Bao Phuong',
    email: 'BPhuong@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0005273933',
  },
  {
    id: 'zLvTQnP',
    name: 'Ho Phap Van',
    email: 'VanHo@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '093125247',
  },
  {
    id: 'MUqlzEn',
    name: 'Ho Gia Phuc',
    email: 'GPhuc@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0770543996',
  },
  {
    id: 'qalUSTX',
    name: 'Pham Hong Thai',
    email: 'Thaihong@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0305499980',
  },
  {
    id: 'ttJrRiK',
    name: 'Phan Van Chuan',
    email: 'ChuanPhan@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0578553108',
  },
  {
    id: 'WuoeizX',
    name: 'Le Van Ngoc',
    email: 'Lengoc@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0993311246',
  },
  {
    id: 'JrZBAxv',
    name: 'Le Ngoc Tien',
    email: 'TienLe@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0998502894',
  },
  {
    id: 'bFACoTt',
    name: 'Pham Gia Anh ',
    email: 'Anhgia@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '096400865',
  },
  {
    id: 'mFKJhEP',
    name: 'Bui Hong Trung',
    email: 'TrungBui@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0967436650',
  },
  {
    id: 'AwrWlAG',
    name: 'Duong Kim Hung',
    email: 'HungDuong@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0204247036',
  },
  {
    id: 'ynAPWkA',
    name: 'Nguyễn Hong Nhat',
    email: 'NhatNguyen@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0214826425',
  },
  {
    id: 'xBhbZuj',
    name: 'Duong Huu Phuong',
    email: 'PhuongDUong@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0214826425',
  },
  {
    id: 'YWWAUcT',
    name: 'Pham Gia Hoang',
    email: 'HoangPham@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0401486748',
  },
  {
    id: 'pmtckUr',
    name: 'Vu Bao Cuong',
    email: 'CuongVu@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0295780135',
  },
  {
    id: 'dIwSGlW',
    name: 'Le Quang Tuan',
    email: 'TuanLe@gmail.com',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0994659752',
  },
];
