3

import type { Teacher } from '.';

export const TeacherData: Teacher[] = [
  {
    id: 'wzoCkgV',
    name: 'Phạm Đăng Hải',
    email: 'haipd@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/000399-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0005273933',
  },
  {
    id: 'eDgUzvz',
    name: 'Nguyễn Linh Giang',
    email: 'giangnl@soict.hust.edu.vn',
    image_url: 'https://soict.hust.edu.vn/wp-content/uploads/IMG_9136_copy.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0280286781',
  },
  {
    id: 'nZLZpPl',
    name: 'Pham Thanh Liem',
    email: ' liem.phamthanh@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/DHP_5377-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0182754393',
  },
  {
    id: 'svyGNxs',
    name: 'Banh Thi Quynh Mai',
    email: 'maibtq@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/DHP_5390-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0996043767',
  },
  {
    id: 'nZLZpPl',
    name: 'Nguyễn Khanh Văn',
    email: 'van.nguyenkhanh@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/DHP_5354-1024x1534.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0760062728',
  },
  {
    id: 'WuoeixS',
    name: 'Hoàng Văn Hiệp',
    email: 'hiephv@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/Hiephv-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0993311244',
  },
  {
    id: 'Eiroksn',
    name: 'Nguyễn Thị Thanh Nga',
    email: 'ngantt@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/08/Nguy%E1%BB%85n-Th%E1%BB%8B-Thanh-Nga-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0998502754',
  },
  {
    id: 'zEICoTt',
    name: 'Lê Tấn Hùng',
    email: 'hunglt@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/letanhung.png',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0957495638',
  },
  {
    id: 'FaJECkl',
    name: 'Tạ Hải Tùng',
    email: ' tung.tahai@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/ta_hai_tung_vt_soict.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0985614225',
  },
  {
    id: 'IxQYRiR',
    name: 'Lã Thé Vinh',
    email: ' vinhlt@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/DHP_5319-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0967088553',
  },
  {
    id: 'RssmilJ',
    name: 'Nguyễn Hữu Đức',
    email: ' duc.nguyenhuu@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/DHP_5851-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0946802461',
  },
  {
    id: 'zvoGVAJ',
    name: 'Phạm Văn Hải',
    email: 'haipv@soict.hust.edu.vn',
    image_url: 'https://soict.hust.edu.vn/wp-content/uploads/HaiPV1.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0246686847',
  },
  {
    id: 'NKKYXlv',
    name: 'Trần Hoàng Hải',
    email: 'hai.tranhoang@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/000381-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0401483748',
  },
  {
    id: 'fwqsHOA',
    name: 'Nguyễn Đức Toàn',
    email: 'toannd@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/nguy%E1%BB%85n-%C4%91%C6%B0c-to%C3%A0n.png',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0295780135',
  },
  {
    id: 'CSXWcBg',
    name: 'Vũ Tuyết Trinh',
    email: 'trinhvt@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/V%C5%A9-Tuy%E1%BA%BFt-Trinh-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0194659952',
  },
  {
    id: 'YQIYjVp',
    name: 'Huỳnh Thị Thanh Bình',
    email: 'binhht@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/08/Hu%E1%BB%B3nh-Th%E1%BB%8B-Thanh-B%C3%ACnh-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0005273933',
  },
  {
    id: 'YojJAgp',
    name: 'Lê Xuân Thành',
    email: 'thanh.lexuan@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/07/20190516_184321.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0098913016',
  },
  {
    id: 'fLioQaV',
    name: 'Nguyễn Đức Tiến',
    email: 'tien.nguyenduc@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/TienND-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0317203621',
  },
  {
    id: 'JaedLdB',
    name: 'Phạm Thị Hương Giang',
    email: 'giangptp@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/GiangPTP.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0609955694',
  },
  {
    id: 'TPHAlsp',
    name: 'Trần Quang Đức',
    email: 'duc.tranquang@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/DHP_5817-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0305876258',
  },
  {
    id: 'EotibRu',
    name: 'Vũ Văn Thiệu',
    email: 'PhuongHynh@gmail.com',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/08/V%C5%A9-V%C4%83n-Thi%E1%BB%87u-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0981483418',
  },
  {
    id: 'IbnkYvv',
    name: 'Cao Tuấn Dũng',
    email: 'dung.caotuan@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/DHP_5196-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0465517472',
  },
  {
    id: 'PUnKhLs',
    name: 'Ngô Lâm Trung',
    email: 'trungnl@soict.hust.edu.vn; trung.ngolam@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/DHP_5810-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0590977309',
  },
  {
    id: 'bliBmAL',
    name: 'Vũ Thị Hương Giang',
    email: 'giangvth@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/08/V%C5%A9-Th%E1%BB%8B-H%C6%B0%C6%A1ng-Giang-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0557473046',
  },
  {
    id: 'GHMssSF',
    name: 'Lê Thanh Hương',
    email: 'huonglt@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/DHP_5526-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0011339419',
  },
  {
    id: 'eyvuhzi',
    name: 'Lê Bá Vui',
    email: 'vui.leba@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/DHP_5811-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0300094400',
  },
  {
    id: 'xbJuhpu',
    name: 'Nguyễn Thị Oanh',
    email: 'oanh.nguyenthi@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/DHP_5827-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0214561343',
  },
  {
    id: 'ircGHHQ',
    name: 'Phạm Ngọc Hưng',
    email: 'hungpn@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/DHP_5317-1-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0521563149',
  },
  {
    id: 'ALbveYV',
    name: 'Trịnh Anh Phúc',
    email: 'phuc.trinhanh@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/000499-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0291906955',
  },
  {
    id: 'cSDdteN',
    name: 'trần Vĩnh Đức',
    email: 'ductv@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/000379-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0751239879',
  },
  {
    id: 'BkGeanD',
    name: 'Bùi Trọng Tùng',
    email: 'tungbt@soict.hust.edu.vn',
    image_url: 'https://soict.hust.edu.vn/wp-content/uploads/IMG_1627.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0554264533',
  },
  {
    id: 'tQVHydK',
    name: 'Phạm Quang Dũng',
    email: 'dungpq@soict.hust.edu.vn',
    image_url: 'https://soict.hust.edu.vn/wp-content/uploads/phamquangdung.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0479508307',
  },
  {
    id: 'NkawAiT',
    name: 'Trần Nguyên Ngọc',
    email: 'ngoctn@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/Tran-Nguyen-Ngoc.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0425111320',
  },
  {
    id: 'JIIKdsO',
    name: 'Nguyễn Đình Thuận',
    email: 'thuan.nguyendinh@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/DHP_5333-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0329782982',
  },
  {
    id: 'RsUfOGs',
    name: 'Đặng Tuấn Linh',
    email: 'linh.dangtuan@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/%C4%90%E1%BA%B7ng-Tu%E1%BA%A5n-Linh-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '"0155927133',
  },
  {
    id: 'JIIKdsO',
    name: 'Trần Nhật Hóa',
    email: 'hoatn@soict.hust.edu.vn',
    image_url: 'https://soict.hust.edu.vn/wp-content/uploads/HoaTN2-1.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0996488343',
  },
  {
    id: 'mDVXNpI',
    name: 'Đỗ Công Thuần',
    email: 'thuan.docong@hust.edu.vn',
    image_url: 'https://soict.hust.edu.vn/wp-content/uploads/Do-Cong-Thuan.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0763697520',
  },
  {
    id: 'ViWgyDJ',
    name: 'Thân Quang Khoát',
    email: 'khoattq@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2018/01/DHP_5171-683x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0916289232',
  },
  {
    id: 'ujbKAdG',
    name: 'Nguyễn Khánh Phương',
    email: ' phuongnk@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/DHP_5231-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0355620816',
  },
  {
    id: 'tGFfSHs',
    name: 'Nguyễn Nhất Hải',
    email: 'hainn@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/Nguy%E1%BB%85n-Nh%E1%BA%A5t-H%E1%BA%A3i-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '044250493',
  },
  {
    id: 'BnYlQow',
    name: 'Nguyễn Thanh Hùng',
    email: ' hungnt@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/DHP_5593-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0946802461',
  },
  {
    id: 'zvoGVAJ',
    name: 'Trần Hải Anh',
    email: 'anhth@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/AnhTH-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0894425049',
  },
  {
    id: 'uUscYpm',
    name: 'Lê Huy Cường',
    email: 'cuong.lehuy@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/DHP_1111-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0300374300',
  },
  {
    id: 'IxWzMaq',
    name: 'Pham Huy Dat',
    email: 'datpd@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/DHP_5268-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0059800522',
  },
  {
    id: 'wOdSKrw',
    name: 'Nguyễn Phi Lê',
    email: 'le.nguyenphi@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/DHP_5245-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0144755108',
  },
  {
    id: 'wzoCkgV',
    name: 'Đỗ Tuấn Anh',
    email: 'anh.dotuan@hust.edu.vn',
    image_url: 'https://soict.hust.edu.vn/wp-content/uploads/AnhDT2.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0005273933',
  },
  {
    id: 'zLvTQnP',
    name: 'Nguyễn Tuấn Dũng',
    email: 'dungnt@soict.hust.edu.vn',
    image_url: 'https://soict.hust.edu.vn/wp-content/uploads/Dung1-copy.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '093125247',
  },
  {
    id: 'MUqlzEn',
    name: 'Nguyễn Hồng Phương',
    email: 'phuongnh@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/DHP_5677-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0770543996',
  },
  {
    id: 'qalUSTX',
    name: 'Ban Hà Băng',
    email: 'bangbh@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/Ban-H%C3%A0-B%E1%BA%B1ng.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0305499980',
  },
  {
    id: 'ttJrRiK',
    name: 'Đỗ Quóc Huy',
    email: 'huydq@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/%C4%90%E1%BB%97-Qu%E1%BB%91c-Huy.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0578553108',
  },
  {
    id: 'WuoeizX',
    name: 'Bùi Thị Mai Anh',
    email: 'anhbtm@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/B%C3%B9i-Th%E1%BB%8B-Mai-Anh-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0993311246',
  },
  {
    id: 'JrZBAxv',
    name: 'Nguyễn Mạnh Tuấn',
    email: 'tuan.nguyenmanh@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/DHP_5611-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0998502894',
  },
  {
    id: 'bFACoTt',
    name: 'Trịnh Văn Loan',
    email: ' loantv@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/LoanTV.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '096400865',
  },
  {
    id: 'mFKJhEP',
    name: 'Nguyễn Thị Hoàng Lan',
    email: 'lan.nguyenthihoang@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/PGS.TS-Nguy%E1%BB%85n-Th%E1%BB%8B-Ho%C3%A0ng-Lan-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0967436650',
  },
  {
    id: 'AwrWlAG',
    name: 'Đặng Văn Chuyét',
    email: 'chuyet.dangvan@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/DHP_5802-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0204247036',
  },
  {
    id: 'ynAPWkA',
    name: 'Phạm Thị Ánh Tuyết',
    email: 'tuyetpta@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/08/tuyet.pa_-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0214826425',
  },
  {
    id: 'xBhbZuj',
    name: 'Vũ Đức Vượng',
    email: 'vuongvd@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/DHP_5779-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0214826425',
  },
  {
    id: 'YWWAUcT',
    name: 'Lê Thị Hoa',
    email: 'hoa.lethi@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/DHP_5172-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0401486748',
  },
  {
    id: 'pmtckUr',
    name: 'Nguyễn Kiêm Hiếu',
    email: 'hieunk@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/DHP_5860-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0295780135',
  },
  {
    id: 'dIwSGlW',
    name: 'Nguyễn Bình Minh',
    email: 'minhnb@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/DHP_5224-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0994659752',
  },
  {
    id: 'ckfZUhV',
    name: 'Nguyễn Bá Ngọc',
    email: 'ngocnb@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/DHP_5807-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0993311246',
  },
  {
    id: 'JrZBAxv',
    name: 'Nguyễn Duy Hiệp',
    email: 'tuan.nguyenmanh@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/DHP_5611-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0998502894',
  },
  {
    id: 'SBoVNQM',
    name: 'Nguyễn Tiến Thành',
    email: 'nguyenthanh@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/ti%E1%BA%BFnthanh.png',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '096400865',
  },
  {
    id: 'qoCNJgx',
    name: 'Trịnh Thành Trung',
    email: 'trungtt@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/trinh-thanh-trung.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0967436650',
  },
  {
    id: 'CGXlwlE',
    name: 'Đỗ Bá Lâm',
    email: 'lam.doba@hust.edu.vn',
    image_url: 'https://soict.hust.edu.vn/wp-content/uploads/2019/06/balam.png',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0204247036',
  },
  {
    id: 'ynAPWkA',
    name: 'Phạm Thị Ánh Tuyết',
    email: 'tuyetpta@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/08/tuyet.pa_-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0214826425',
  },
  {
    id: 'VsVUBRe',
    name: 'Trần Việt Trung',
    email: 'trungtv@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/06/DHP_5324-1-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0214826425',
  },
  {
    id: 'ZpjOPax',
    name: 'Đinh Viết Sang',
    email: 'sangdv@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/DHP_5925-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0401486748',
  },
  {
    id: 'yByPqcM',
    name: 'Trịnh Tuấn Đạt',
    email: 'dattt@soict.hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2017/03/DHP_5367-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0295780135',
  },
  {
    id: 'dIwSGlW',
    name: 'Nguyễn Kim Khánh',
    email: 'khanh.nguyenkim@hust.edu.vn',
    image_url:
      'https://soict.hust.edu.vn/wp-content/uploads/2019/08/Nguy%E1%BB%85n-Kim-Kh%C3%A1nh-684x1024.jpg',
    created_at: new Date(),
    updated_at: new Date(),
    phone: '0994659752',
  },
];
